system 100
{
	technique
	{
		position						0 8 5
		material						100
		default_particle_width			14 

		default_particle_height			7 

		use_alias						$defaultBillboardRenderer
		emitter							Point
		{
			force_emission				true
			emission_rate				1
			angle					0
			direction				0 0 0
			velocity				0
			time_to_live				100000

		}

		}

	}
