system 2x
{
	technique
	{
		position						0 6 0
		material						2x
		default_particle_width			3

		default_particle_height			1.5 

		use_alias						$defaultBillboardRenderer
		emitter							Point
		{
			force_emission				true
			emission_rate				1
			angle					0
			direction				0 0 0
			velocity				0
			time_to_live				100000

		}

		}

}