system 90
{
	technique
	{
		position						0 8 5
		material						90
		default_particle_width			13 

		default_particle_height			6.5 

		use_alias						$defaultBillboardRenderer
		emitter							Point
		{
			force_emission				true
			emission_rate				1
			angle					0
			direction				0 0 0
			velocity				0
			time_to_live				100000

		}

		}

	}
