// ------------------------------------------- Begin: Explosion system -------------------------------------------
// The explosion system is an example of a complex particle system.
// Note, that the Projectiles and debris are not emitted immediately, but only after some time to make the effect
// look a bit more realistic.
// ---------------------------------------------------------------------------------------------------------------
system test
{
	// --------------- Clouds ---------------
	technique
	{
		use_alias						$defaultBillboardRenderer
		material						cloud
		default_particle_width			5
		default_particle_height			5
		visual_particle_quota			500
		emitter							SphereSurface		BurstEmitter
		{
			emission_rate				20
			auto_direction				true
			sphere_surface_em_radius		5
			velocity				500
//			time_to_live				.5
		}
		
		// Change the colour of the burst
		affector						Colour
		{
			colour_aff_time_colour		0 1 0 0 1
			colour_aff_time_colour		0.5 0 1 0 .5
			colour_aff_time_colour		1 0 0 1 0
		}
		
		// Let it grow fast, equally in all dimensions
		affector						Scale
		{
			xyz_scale					dyn_curved_linear
		{
			    control_point       0 1
			    control_point       0.1 100
			    control_point       0.5 100
		}
		}


		// After 0.7 seconds, the emitters stops
//		observer						OnTime
//		{
//			on_time						greater_than 0.3
//			since_start_system			true
//			handler						DoEnableComponent
//			{
//				enable_component		emitter_component	BurstEmitter	false
//			}
//		}
	}
	

}
// ---------------------------------------------- End: Explosion system ----------------------------------------------
